apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # Injects simple key-value configurations
  {{-- if .Values.configData }}
  {{-- .Values.configData | toYaml | nindent 2 }}
  {{-- end }}

  # Injects larger, multiline configuration files (like app.json or nginx.conf)
  {{-- range $key, $value := .Values.configFiles }}
  {{ $key }}: |
    {{-- $value | nindent 4 }}
  {{-- end }}

