---
- name: Print Message Workflow
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World! Jenkins executed this Ansible playbook successfully."

    - name: Print current date
      command: date
      register: current_date

    - name: Display current date
      debug:
        var: current_date.stdout
